### ISSUE TITLE
Idée

### ISSUE THREAD

**Issue by unknow-user0** [KanekiWeb/GIVE-IDEAS#4]
Un phone bouncer ou un logiciel pour commencer le spamming

**Comment by KanekiWeb** [comment]
## **Déja fais** 

![](https://media.discordapp.net/attachments/969664876538654812/975439366837112892/unknown.png?width=1024&height=426)

![](https://media.discordapp.net/attachments/969664876538654812/975439394595033118/unknown.png?width=882&height=465)
